<?php
// Sharetronix Dynamic Google SiteMap File
// Generated by Gokhan MERCANOGLU
// Edited by guy18iran - www.Sharetronix.ir
error_reporting(E_ALL & ~E_NOTICE); // For error Reporting 

// Database information
include("./system/conf_main.php");
$Server =	$C->DB_HOST;
$user =		$C->DB_USER;
$password =	$C->DB_PASS;
$dbname	=	$C->DB_NAME;
$siteurl =	$C->SITE_URL;

// Start to site map generation
$update = date("Y-m-d H:i:s"); 
header("Content-Type: text/xml"); 
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?> <urlset xmlns=\"http://www.google.com/schemas/sitemap/0.84\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"  xsi:schemaLocation=\"http://www.google.com/schemas/sitemap/0.84 http://www.google.com/schemas/sitemap/0.84/sitemap.xsd\">\n";  
echo "<!-- Persian Sharetronix - www.Sharetronix.ir -->\n";

$db=mysql_connect($server,$user,$password);
    mysql_query("SET NAMES 'utf8'");
    mysql_select_db($dbname, $db);
//User Map
$i = 1;
  $Query1 = "SELECT username FROM users ORDER BY `id` desc";
  $QueryResult = @mysql_query($Query1);
     if (@mysql_num_rows($QueryResult)>0){
         while ($entry=@mysql_fetch_assoc($QueryResult))
		 {
             $EntryResult=$entry["username"];          
			 echo " <url> 
                  <loc>".$siteurl.$EntryResult."</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n"; 
$i++;
}
}
//Group Map

$i = 1;
  $Query1 = "SELECT groupname FROM groups ORDER BY `id` desc";
  $QueryResult = @mysql_query($Query1);
     if (@mysql_num_rows($QueryResult)>0){
         while ($entry=@mysql_fetch_assoc($QueryResult))
		 {
             $EntryResult=$entry["groupname"];          
			 echo " <url> 
                  <loc>".$siteurl.$EntryResult."</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n"; 
$i++;
}
}
// Post Map 

$i = 1;
  $Query1 = "SELECT `id` FROM posts WHERE (`user_id` >0) and (`api_id`=0) ORDER BY `id` desc";
  $QueryResult = @mysql_query($Query1);
     if (@mysql_num_rows($QueryResult)>0){
         while ($entry=@mysql_fetch_assoc($QueryResult))
		 {
             $EntryResult=$entry["id"];          
			 echo " <url> 
                  <loc>".$siteurl."view/post:".$EntryResult."</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n"; 
$i++;
}
}
//General Site Map

            echo " <url> 
                  <loc>".$siteurl."members</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n"; 
          echo " <url> 
                  <loc>".$siteurl."search/</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n"; 
		            echo " <url> 
                  <loc>".$siteurl."members</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n"; 
          echo " <url> 
                  <loc>".$siteurl."groups/</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n";   
          echo " <url> 
                  <loc>".$siteurl."contacts/</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n";  
          echo " <url> 
                  <loc>".$siteurl."m/</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n";
          echo " <url> 
                  <loc>".$siteurl."faq/</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n";  			  
          echo " <url> 
                  <loc>".$siteurl."groups/tab:all/</loc> 
                  <lastmod>$date</lastmod> 
                  <changefreq>daily</changefreq> 
                 <priority>0.5</priority> 
          </url>\n";  			  
echo '</urlset>';
?>